codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: develop
  branch: develop

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      backend:
        target: 90%
        threshold: 0%
        paths: "cmd"
    patch:
      backend:
        target: 90%
        paths: "cmd"
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
